# Generated by Django 4.2.4 on 2023-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
